// Generated by CoffeeScript 1.6.3
var AWS, fibrous, getMostRecentBackup, lazy, optimist, progress, s3, through;

fibrous = require('fibrous');

lazy = require('lazy.js');

progress = require('progress');

through = require('through');

optimist = require('optimist');

AWS = require('aws-sdk');

s3 = new AWS.S3({
  apiVersion: '2006-03-01'
});

getMostRecentBackup = fibrous(function(bucket) {
  return lazy(s3.sync.listObjects({
    Bucket: bucket,
    Prefix: 'mongohq_backups/'
  }).Contents).max('LastModified');
});

(fibrous(function() {
  var mostRecent;
  mostRecent = getMostRecentBackup.sync(optimist.argv.bucket);
  s3.getObject({
    Bucket: bucket,
    Key: mostRecent.Key
  }).createReadStream().pipe(process.stdout);
}))(function(err, response) {
  if (err != null) {
    throw err;
  }
  if (response != null) {
    return console.log(response);
  }
});
