// Generated by CoffeeScript 1.6.3
var lazy, moment, s3;

moment = require('moment');

lazy = require('lazy.js');

s3 = require('./s3');

module.exports = {
  getMostRecentBackup: function(bucket, prefix, before, callback) {
    return s3.listObjects({
      Bucket: bucket,
      Prefix: prefix
    }, function(err, objects) {
      var object;
      if (err != null) {
        callback(err);
      }
      object = lazy((objects != null ? objects.Contents : void 0) || []).filter(function(object) {
        return moment(object.LastModified).isBefore(before);
      }).max('LastModified');
      if (object == null) {
        callback(new Error("Could not find any objects in bucket " + (JSON.stringify(bucket)) + " with prefix " + (JSON.stringify(prefix)) + " modified before " + (moment(before).format('dddd, MMMM Do YYYY, h:mm:ss a ZZ'))));
      }
      return callback(null, object);
    });
  }
};
