// Generated by CoffeeScript 1.6.3
var lazy, s3;

lazy = require('lazy.js');

s3 = require('./s3');

module.exports = {
  getMostRecentBackup: function(bucket, prefix, callback) {
    return s3.listObjects({
      Bucket: bucket,
      Prefix: prefix
    }, function(err, objects) {
      return callback(err, lazy((objects != null ? objects.Contents : void 0) || []).max('LastModified'));
    });
  }
};
