// Generated by CoffeeScript 1.6.3
var argv, conf, confSchema, convict, e, helpAndQuit, optimist, versionAndQuit;

convict = require('convict');

optimist = require('optimist');

confSchema = {
  bucket: {
    doc: "The S3 bucket to download from",
    format: "*",
    "default": null,
    env: "AWS_S3_BUCKET",
    arg: "bucket"
  },
  prefix: {
    doc: "Filter items by names starting with this string",
    format: "*",
    "default": "",
    env: "AWS_S3_PREFIX",
    arg: "prefix"
  },
  access_key: {
    doc: "Your AWS access key",
    env: "AWS_ACCESS_KEY",
    "default": null
  },
  secret: {
    doc: "Your AWS access key secret",
    env: "AWS_SECRET_ACCESS_KEY",
    "default": null
  }
};

helpAndQuit = function() {
  var help, key, line, pkgInfo, val;
  pkgInfo = require('../package.json');
  help = [pkgInfo.description];
  for (key in confSchema) {
    val = confSchema[key];
    line = "[env: " + val.env + "] " + val.doc;
    if (val.arg != null) {
      line = "--" + val.arg + " " + line;
    }
    if (val["default"] == null) {
      line = "" + line + " (required)";
    }
    help.push(line);
  }
  console.log(help.join('\n'));
  return process.exit(0);
};

versionAndQuit = function() {
  var pkgInfo;
  pkgInfo = require('../package.json');
  console.log("" + pkgInfo.name + " " + pkgInfo.version);
  return process.exit(0);
};

argv = optimist.alias({
  help: 'h',
  version: 'v'
}).argv;

if (argv.help != null) {
  helpAndQuit();
}

if (argv.version != null) {
  versionAndQuit();
}

module.exports = conf = convict(confSchema);

try {
  conf.validate();
} catch (_error) {
  e = _error;
  helpAndQuit();
}
