// Generated by CoffeeScript 1.6.3
var conf, fibrous, finder, progress, s3, through;

fibrous = require('fibrous');

progress = require('progress');

through = require('through');

conf = require('./conf');

finder = require('./backup_finder');

s3 = require('./s3');

(fibrous(function() {
  var mostRecent;
  mostRecent = finder.getMostRecentBackup.sync(conf.bucket);
  s3.getObject({
    Bucket: conf.bucket,
    Key: mostRecent.Key
  }).createReadStream().pipe(process.stdout);
}))(function(err, response) {
  if (err != null) {
    throw err;
  }
  if (response != null) {
    return console.log(response);
  }
});
