// Generated by CoffeeScript 1.6.3
var conf, fibrous, finder, s3;

fibrous = require('fibrous');

conf = require('./conf');

finder = require('./backup_finder');

s3 = require('./s3');

(fibrous(function() {
  var mostRecent;
  mostRecent = finder.getMostRecentBackup.sync(conf.get('bucket'), conf.get('prefix'));
  s3.getObject({
    Bucket: conf.get('bucket'),
    Key: mostRecent.Key
  }).createReadStream().pipe(process.stdout);
}))(function(err, response) {
  if (err != null) {
    throw err;
  }
  if (response != null) {
    return console.log(response);
  }
});
