// Generated by CoffeeScript 1.6.3
var conf, convict;

convict = require('convict');

module.exports = conf = convict({
  bucket: {
    doc: "The S3 bucket to download from",
    format: "*",
    "default": null,
    env: "AWS_S3_BUCKET",
    arg: "bucket"
  }
});

conf.validate();
